import json

with open('src/locales/es.json', 'r') as f:
    es_json = json.load(f)

translations = {
  "Casa Nieves": "Casa Nieves",
  "15 m\u00b2": "15 m\u00b2",
  "Casa Mochila": "Casa Mochila",
  "21 m\u00b2": "21 m\u00b2",
  "Casa Flores": "Casa Flores",
  "19 m\u00b2": "19 m\u00b2",
  "Casa Volc\u00e1n": "Casa Volc\u00e1n",
  "A/C": "Aire Acondicionado",
  "TV": "TV",
  "Patio": "Patio",
  "Google": "Google",
  "Casa": "Casa",
  "Ruta de las Flores": "Ruta de las Flores",
  "Apaneca": "Apaneca",
  "A striking emerald-green crater lake cradled inside an extinct volcanic caldera.": "Una impresionante laguna de cr\u00e1ter verde esmeralda acunada dentro de una caldera volc\u00e1nica extinta.",
  "High-altitude zip-line adventure through cloud-forest canopy with panoramic ridge views.": "Aventura en tirolesa a gran altura a trav\u00e9s del dosel del bosque nuboso con vistas panor\u00e1micas a la cordillera.",
  "Award-winning coffee farm offering guided tours from seed to cup.": "Finca de caf\u00e9 galardonada que ofrece visitas guiadas desde la semilla hasta la taza.",
  "Ataco": "Ataco",
  "Cobblestone streets lined with vivid pastel murals painted by local and international artists.": "Calles empedradas bordeadas de v\u00edvidos murales en colores pastel pintados por artistas locales e internacionales.",
  "A colorful artisan market selling handwoven textiles, ceramics, and woodwork.": "Un colorido mercado de artesan\u00edas que vende textiles tejidos a mano, cer\u00e1mica y carpinter\u00eda.",
  "Cloud forest reserve with rare wildlife, volcanic lookouts, and challenging trails nearby.": "Reserva de bosque nuboso con vida silvestre rara, miradores volc\u00e1nicos y senderos desafiantes cercanos.",
  "when you book direct with us via WhatsApp or our website, no platform fees, more money stays in the highlands.": "al reservar directamente con nosotros v\u00eda WhatsApp o en nuestra web, no hay cargos de plataforma y m\u00e1s dinero se queda en las tierras altas.",
  "Neskapolita": "Neskapolita",
  "Laguna Las Ninfas": "Laguna Las Ninfas",
  "Laguna Verde": "Laguna Verde",
  "Canopy Apaneca": "Canopy Apaneca",
  "Finca Santa Leticia": "Finca Santa Leticia",
  "Mercado de Artesan\u00edas": "Mercado de Artesan\u00edas",
  "Parque Central": "Parque Central",
  "Mercado Nocturno": "Mercado Nocturno",
  "Iglesia de Nahuizalco": "Iglesia de Nahuizalco",
  "Cascada El Escuco": "Cascada El Escuco",
  "Book Your Stay": "Reserva Tu Estad\u00eda",
  "PayPal": "PayPal",
  "Cash (USD)": "Efectivo (USD)",
  "VISA": "VISA",
  "Cards Accepted": "Se Aceptan Tarjetas",
  "Free cancellation within 48h": "Cancelaci\u00f3n gratuita en 48h",
  "We accept various ways to pay so you can focus on the adventure": "Aceptamos varias formas de pago para que puedas concentrarte en la aventura",
  "Explore the must-visit spots": "Explora los lugares de visita obligada",
  "24/7 washers and dryers so you can pack light and stay fresh.": "Lavadoras y secadoras 24/7 para que viajes ligero y te mantengas fresco.",
  "Cozy community space with deep couches, books, and vinyl records.": "Acogedor espacio comunitario con c\u00f3modos sof\u00e1s, libros y discos de vinilo.",
  "Fully equipped space to cook, share recipes, and connect over food.": "Espacio totalmente equipado para cocinar, compartir recetas y conectar en torno a la comida.",
  "A lush, tranquil green oasis to unwind, read, or enjoy morning coffee.": "Un frondoso y tranquilo oasis verde para relajarse, leer o disfrutar del caf\u00e9 de la ma\u00f1ana.",
  "Casa nieves": "Casa Nieves",
  "Chambre Twin avec salle de bain priv\u00e9e": "Habitaci\u00f3n doble con ba\u00f1o privado",
  "Rooms": "Habitaciones",
  "Story": "Historia",
  "Find Us": "Encu\u00e9ntranos",
  "EN": "EN",
  "ES": "ES",
  "Book Now": "Reserva Ahora",
  "Booking raiting": "Puntuaci\u00f3n de Booking",
  "From shared dorms to private rooms with a view \u2014 every space at Neskapolita has its own story to tell.": "Desde dormitorios compartidos hasta habitaciones privadas con vista: cada espacio en Neskapolita tiene su propia historia que contar.",
  "Secure booking \u00b7 No hidden fees \u00b7 Free cancellation within 48h": "Reserva segura \u00b7 Sin tarifas ocultas \u00b7 Cancelaci\u00f3n gratis en 48h",
  "you need": "que necesitas",
  "for a perfect stay": "para una estancia perfecta",
  "Explore the must-visit spots.": "Explora los lugares imprescindibles.",
  "Your refuge on the Ruta de las flores. Juayu\u00e1, El Salvador.": "Tu refugio en la Ruta de las flores. Juay\u00faa, El Salvador.",
  "\u00a9 2026 Neskapolita Hostel": "\u00a9 2026 Neskapolita Hostel",
  "Stay": "Estad\u00eda",
  "FAQ": "Preguntas Frecuentes",
  "Gallery": "Galer\u00eda",
  "Connect": "Conectar",
  "Instagram": "Instagram",
  "WhatsApp": "WhatsApp",
  "on the Ruta de las flores": "en la Ruta de las flores",
  "Google raiting": "Puntuaci\u00f3n de Google",
  "1,100m": "1,100m",
  "Above Sea Level": "Sobre el nivel del mar",
  "when you book direct with us via WhatsApp or our website \u2014 no platform fees, more money stays in the highlands.": "cuando reservas directamente con nosotros por WhatsApp o nuestra web \u2014 sin cargos de plataforma, m\u00e1s dinero se queda en las monta\u00f1as.",
  "Private Rooms": "Habitaciones Privadas",
  "Dormitory": "Dormitorio",
  "Getting Here": "C\u00f3mo Llegar",
  "Facebook": "Facebook",
  "Juay\u00faa": "Juay\u00faa",
  "A series of stunning cascades fed by volcanic springs, ideal for swimming.": "Una serie de impresionantes cascadas alimentadas por manantiales volc\u00e1nicos, ideales para nadar.",
  "Open-air market every weekend overflowing with local pupusas, grilled meats, and fresh juices.": "Mercado al aire libre cada fin de semana repleto de pupusas locales, carnes asadas y jugos frescos.",
  "A peaceful volcanic lagoon surrounded by lush highland forest \u2014 perfect for sunrise hikes.": "Una pac\u00edfica laguna volc\u00e1nica rodeada de exuberante bosque de altura \u2014 perfecta para caminatas al amanecer.",
  "booking raiting": "puntuaci\u00f3n de booking",
  "Nahuizalco": "Nahuizalco",
  "Watch master artisans weave ancestral Nahua basketry and furniture using tule reed.": "Mira a los maestros artesanos tejer cester\u00eda y muebles ancestrales nahuas usando tule.",
  "Book via WhatsApp": "Reservar por WhatsApp",
  "Explore Ruta": "Explorar Ruta",
  "Booking": "Reservas",
  "Dark": "Oscuro",
  "explore \u201cruta de las flores\u201d": "explorar \u201cruta de las flores\u201d",
  "Set in the heart of Juay\u00faa, Neskapolita makes exploring the region effortless": "Ubicado en el coraz\u00f3n de Juay\u00faa, Neskapolita hace que explorar la regi\u00f3n sea muy f\u00e1cil",
  "Discover the best of Juay\u00faa and neighboring mountain towns from the famous weekend food festival and coffee farms to hidden waterfalls and colonial artisan markets.": "Descubre lo mejor de Juay\u00faa y los pueblos de monta\u00f1a vecinos, desde el famoso festival gastron\u00f3mico de fin de semana y fincas cafetaleras hasta cascadas ocultas y mercados artesanales coloniales.",
  "STOP 1": "PARADA 1",
  "Get Route Directions": "Obtener Direcciones",
  "STOP 2": "PARADA 2",
  "8 km north": "8 km al norte",
  "STOP 3": "PARADA 3",
  "12 km north": "12 km al norte",
  "STOP 4": "PARADA 4",
  "5 km south": "5 km al sur",
  "Salcoatit\u00e1n": "Salcoatit\u00e1n",
  "STOP 5": "PARADA 5",
  "15 km south": "15 km al sur",
  "Candlelit Night Market": "Mercado Nocturno",
  "STOP 6": "PARADA 6",
  "25 km south": "25 km al sur",
  "Sonsonate": "Sonsonate",
  "Book your stay at Neskapolita in Juay\u00faa\u2014the perfect, central base for all your western mountain adventures.": "Reserva tu estad\u00eda en Neskapolita en Juay\u00faa\u2014la base c\u00e9ntrica perfecta para todas tus aventuras en las monta\u00f1as occidentales.",
  "How many days do you need for Ruta de las Flores?": "\u00bfCu\u00e1ntos d\u00edas necesitas para la Ruta de las Flores?",
  "We recommend 2 to 3 days to fully explore the food markets, hike to waterfalls, and tour coffee farms at a relaxed highland pace.": "Recomendamos de 2 a 3 d\u00edas para explorar a fondo los mercados gastron\u00f3micos, caminar hasta las cascadas y recorrer las fincas cafetaleras a un ritmo relajado.",
  "What is the best town to visit in Ruta de las Flores?": "\u00bfCu\u00e1l es el mejor pueblo para visitar en la Ruta de las Flores?",
  "Juay\u00faa is the perfect culinary and adventure hub, while Ataco shines with its street art, and Apaneca offers high-altitude nature.": "Juay\u00faa es el centro culinario y de aventuras perfecto, mientras que Ataco brilla por su arte callejero, y Apaneca ofrece naturaleza a gran altitud.",
  "Can you visit Ruta de las Flores without a car?": "\u00bfSe puede visitar la Ruta de las Flores sin coche?",
  "What is the best time of year to visit Ruta de las Flores?": "\u00bfCu\u00e1l es la mejor \u00e9poca del a\u00f1o para visitar la Ruta de las Flores?",
  "The dry season from November to April offers beautiful sunny weather, but the green season (May to October) makes waterfalls spectacular.": "La estaci\u00f3n seca, de noviembre a abril, ofrece un hermoso clima soleado, pero la estaci\u00f3n verde (de mayo a octubre) hace que las cascadas sean espectaculares.",
  "Your tropical refuge in the high coffee lands. The perfect basecamp for wandering painters, hikers, and curious souls.": "Tu refugio tropical en las altas tierras cafetaleras. El campamento base perfecto para pintores, excursionistas y almas curiosas.",
  "Calle Merceditas Caceres 1-5, 01101 Juay\u00faa, El Salvador": "Calle Merceditas C\u00e1ceres 1-5, 01101 Juay\u00faa, El Salvador",
  "Town Guide": "Gu\u00eda del Pueblo",
  "Los Chorros": "Los Chorros",
  "Food Festival": "Festival Gastron\u00f3mico",
  "Hostel": "Hostal",
  "Our Rooms": "Nuestras Habitaciones",
  "The Garden": "El Jard\u00edn",
  "Shared Kitchen": "Cocina Compartida",
  "\u00a9 2026 Neskapolita Hostel. Handcrafted in El Salvador.": "\u00a9 2026 Neskapolita Hostel. Hecho a mano en El Salvador.",
  "Designed for Adventure": "Dise\u00f1ado para la Aventura",
  "The tranquil central park framed by colonial architecture and flowering gardens.": "El tranquilo parque central enmarcado por arquitectura colonial y jardines florecientes.",
  "Family-run galleries showcasing intricate hand-carved furniture and traditional wooden crafts.": "Galer\u00edas familiares que exhiben muebles tallados a mano y artesan\u00edas de madera tradicionales.",
  "An imposing Baroque cathedral built in the 18th century with ornate gold-leaf altarpieces.": "Una imponente catedral barroca construida en el siglo XVIII con retablos ornamentados en pan de oro.",
  "Natural volcanic thermal pools with mineral-rich waters \u2014 a perfect post-hike recovery spot.": "Piscinas termales volc\u00e1nicas naturales con aguas ricas en minerales \u2014 un lugar de recuperaci\u00f3n perfecto despu\u00e9s de una caminata.",
  "A hidden multi-tiered waterfall deep in the Nahuaterique mountains, reached via jungle trail.": "Una cascada oculta de m\u00faltiples niveles en lo profundo de las monta\u00f1as de Nahuaterique, a la que se accede por un sendero en la selva."
}

def update_dict(d):
    for k, v in d.items():
        if isinstance(v, dict):
            update_dict(v)
        elif v in translations:
            d[k] = translations[v]
        elif v.endswith('(ES)'):
            base_v = v[:-5].strip()
            if base_v in translations:
                d[k] = translations[base_v]

update_dict(es_json)

with open('src/locales/es.json', 'w') as f:
    json.dump(es_json, f, indent=2, ensure_ascii=False)

print("Updated es.json")
